# Default values for voting-app Helm chart

# Database
postgresql:
  image: postgres:15-alpine
  replicaCount: 1
  service:
    type: ClusterIP
    port: 5432
  credentials:
    username: postgres
    password: postgres
  persistence:
    enabled: true
    mountPath: /var/lib/postgresql/data

# Redis
redis:
  image: redis:alpine
  replicaCount: 1
  service:
    type: ClusterIP
    port: 6379
  persistence:
    enabled: true
    mountPath: /data

# Vote App
vote:
  image: ghcr.io/charanprajwal/example-voting-app-ci/vote@sha256:c34d230771b6a352ab21f22c8de9bcc04d320add0c78cbf688b2ebd82f3b1bef
  replicaCount: 1
  service:
    type: NodePort
    port: 8080
    targetPort: 80
    nodePort: 31000

# Result App
result:
  image: ghcr.io/charanprajwal/example-voting-app-ci/result@sha256:595bc33df00c18e1fdcf63ac348ec2d08239305915331f0650236136d1216306
  replicaCount: 1
  service:
    type: NodePort
    port: 8081
    targetPort: 80
    nodePort: 31001

# Worker
worker:
  image: ghcr.io/charanprajwal/example-voting-app-ci/worker@sha256:78851b21463d03034895dbc320861adf2dadea544e99ead9b4cd683a808fed03
  replicaCount: 1
