# Default values for voting-app Helm chart

# Database
postgresql:
  image: postgres:15-alpine
  replicaCount: 1
  service:
    type: ClusterIP
    port: 5432
  credentials:
    username: postgres
    password: postgres
  persistence:
    enabled: true
    mountPath: /var/lib/postgresql/data

# Redis
redis:
  image: redis:alpine
  replicaCount: 1
  service:
    type: ClusterIP
    port: 6379
  persistence:
    enabled: true
    mountPath: /data

# Vote App
vote:
  image: dockersamples/examplevotingapp_vote
  replicaCount: 1
  service:
    type: NodePort
    port: 8080
    targetPort: 80
    nodePort: 31000

# Result App
result:
  image: dockersamples/examplevotingapp_result
  replicaCount: 1
  service:
    type: NodePort
    port: 8081
    targetPort: 80
    nodePort: 31001

# Worker
worker:
  image: dockersamples/examplevotingapp_worker
  replicaCount: 1
