apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: ghcr.io/charanprajwal/example-voting-app-ci/worker@ghcr.io/charanprajwal/example-voting-app-ci/worker@sha256:fc2c0f1cd1f1aee5e6a0d40344ae4ceab13c87cf40df1ab7f97082d285cca6db
        name: worker 