---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  labels:
    app: db
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgresql.credentials.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.credentials.password | b64enc | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  replicas: {{ .Values.postgresql.replicaCount }}
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgresql.image }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - mountPath: {{ .Values.postgresql.persistence.mountPath }}
              name: db-data
      volumes:
        - name: db-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - name: db-service
      port: {{ .Values.postgresql.service.port }}
      targetPort: 5432
  selector:
    app: db 