---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  labels:
    app: result
spec:
  replicas: {{ .Values.result.replicaCount }}
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - name: result
          image: {{ .Values.result.image }}
          ports:
            - containerPort: 80
              name: result
---
apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
spec:
  type: {{ .Values.result.service.type }}
  ports:
    - name: result-service
      port: {{ .Values.result.service.port }}
      targetPort: {{ .Values.result.service.targetPort }}
      nodePort: {{ .Values.result.service.nodePort }}
  selector:
    app: result 